#---
#
#deploy_check_display_confirmation_prompts: true
#
#base_show_production_login_warning: true
#base_install_updates_automatically: true
#
#backend_server_name: "<your-production-server-backend-cname>"
#
#frontend_server_name: "<your-production-server-frontend-cname>"
#
## See README.txt - store sensitive variables like this using ansible vault
#database_password: "<your-production-database-password>"
#
# firewalld_zones:
#  - name: backend
#    ip_addresses:
#     - <your-production-backend-ip-address>
#
# firewalld_additional_rules: []
#
#ssl_provider: 'certbot'
#ssl_certbot_email: '<your-certbot-notification-email>'
