#---
#
#backend_app_user: "{{ cookiecutter.project_slug }}"
#backend_app_group: "{{ cookiecutter.project_slug }}"
{% raw %}
#backend_app_vagrant_mount: false
#backend_app_debug: false
#backend_app_database_host: "<your-production-database-host>"
## To generate a new secret key using django:
## $ python manage.py shell
## >>> from django.core.management import utils
## >>> utils.get_random_secret_key()
##
## See README.txt - store sensitive variables like this using ansible vault
#backend_app_secret_key: "<your-production-django-secret-key>"
#backend_app_cors_origin_whitelist:
#  - "https://{{ frontend_server_name }}"
#backend_app_allowed_hosts:
#  - "{{ backend_server_name }}"
{% endraw %}
